config/routes.rb
Rails.application.routes.draw do

  resources :scores
  resources :students
  resources :subjects
  resources :teachers
  root 'welcome#index'
  resources :assigneds

  namespace :api ,defaults: {format: :json}do
    namespace :v1 do
        resources :subjects
        resources :scores
        get 'login/attemp'
        get 'login/student'
        get  'assigneds/get_subjects'
    end
  end
  
end

app/models/teacher.rb
class Teacher < ActiveRecord::Base

	def self.login(user,psw)
		where("user = ? AND password = ?",user,psw)
	end


	def self.encrypt(newpassword)
		privateKey = "@aplication_wcode(encrypt)@"
		key = Digest::MD5.hexdigest(privateKey) 
		val = key+newpassword
		code = Digest::MD5.hexdigest(val)
		p = Digest::SHA256.hexdigest(code)
		return p
	end
	
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :set_teacher, only: [:show, :edit, :update, :destroy]

  # GET /teachers
  # GET /teachers.json
  def index
    @teachers = Teacher.all
  end

  # GET /teachers/1
  # GET /teachers/1.json
  def show
  end

  # GET /teachers/new
  def new
    @teacher = Teacher.new
  end

  # GET /teachers/1/edit
  def edit
  end

  # POST /teachers
  # POST /teachers.json
  def create
    @teacher = Teacher.new(teacher_params)
    @teacher.password=Teacher.encrypt(params[:teacher][:password])
    respond_to do |format|
      if @teacher.save
        format.html { redirect_to @teacher, notice: 'Teacher was successfully created.' }
        format.json { render :show, status: :created, location: @teacher }
      else
        format.html { render :new }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teachers/1
  # PATCH/PUT /teachers/1.json
  def update
    respond_to do |format|
      if @teacher.update(teacher_params)
        format.html { redirect_to @teacher, notice: 'Teacher was successfully updated.' }
        format.json { render :show, status: :ok, location: @teacher }
      else
        format.html { render :edit }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teachers/1
  # DELETE /teachers/1.json
  def destroy
    @teacher.destroy
    respond_to do |format|
      format.html { redirect_to teachers_url, notice: 'Teacher was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_teacher
      @teacher = Teacher.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def teacher_params
      params.require(:teacher).permit(:name, :lastname, :user, :password)
    end
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/teachers/_form.html.erb
<%= form_for(@teacher) do |f| %>
  <% if @teacher.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@teacher.errors.count, "error") %> prohibited this teacher from being saved:</h2>

      <ul>
      <% @teacher.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :lastname %><br>
    <%= f.text_field :lastname %>
  </div>
  <div class="field">
    <%= f.label :user %><br>
    <%= f.text_field :user %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/teachers/edit.html.erb
<h1>Editing Teacher</h1>

<%= render 'form' %>

<%= link_to 'Show', @teacher %> |
<%= link_to 'Back', teachers_path %>

app/views/teachers/index.html.erb
<div class="row">
  <div class="col s12 m12 l12">
    <div class="row">
      <h3 class="center-align">Lista de Maestros</h3>
    </div>
    <div class="row">
      <div class="row padding-largo">
        <table class="table">
          <thead>
            <tr>
              <th>Nombre</th>
              <th>Apellidos</th>
              <th>Usuario</th>
              <th></th>
            </tr>
          </thead>

          <tbody>
            <% @teachers.each do |teacher| %>
              <tr>
                <td><%= teacher.name %></td>
                <td><%= teacher.lastname %></td>
                <td><%= teacher.user %></td>
                <td>
                  <%= link_to 'Ver', teacher , class: 'btn'%>
                  <%= link_to 'Editar', edit_teacher_path(teacher) , class: 'btn'%>
                  <%= link_to 'Eliminar', teacher, method: :delete, data: { confirm: 'Are you sure?' } , class: 'btn'%>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
        </table>
      </div>

      <div class="row padding-largo">
        <%= link_to 'Agregar Maestro', new_teacher_path, class: 'btn blue' %>        
      </div>

    </div>
  </div>
</div>

app/views/teachers/new.html.erb
<h1>New Teacher</h1>

<%= render 'form' %>

<%= link_to 'Back', teachers_path %>

app/views/teachers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @teacher.name %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @teacher.lastname %>
</p>

<p>
  <strong>User:</strong>
  <%= @teacher.user %>
</p>

<p>
  <strong>Password:</strong>
  <%= @teacher.password %>
</p>

<%= link_to 'Edit', edit_teacher_path(@teacher) %> |
<%= link_to 'Back', teachers_path %>